# model args
model: outputs/PathVerse/1_sft/qwen2-vl-7b-base_0625+rsn-0108+RD_full_VAL_2/v1-20260118-163824/checkpoint-11804
output_dir: outputs/PathVerse/2_mid/0625+rsn-0108+RD#RefPath+aux/v0-20260122-141159
torch_dtype: bfloat16
attn_impl: flash_attn
freeze_vit: false
freeze_aligner: false
add_version: false 

# data args
dataset: 
  - 'datasets_public/RefPath/refpath_train_convs_RL-half.json'
val_dataset:
  - 'datasets_public/RefPath/refpath_testB.json'
dataset_num_proc: 16
load_from_cache_file: true
dataloader_num_workers: 4
max_length: 8192 # 在GRPO时代表max_prompt_length

# log, val and save args
logging_steps: 1
save_strategy: steps
save_steps: 40
save_total_limit: 2
save_only_model: false
report_to: swanlab
swanlab_project: CGPO_middle
swanlab_exp_name: RL_for_RefPath

# train args
train_type: full
deepspeed: zero3
gradient_checkpointing: true
learning_rate: 1e-6
lr_scheduler_type: constant
weight_decay: 0.01
warmup_ratio: 0.0
num_train_epochs: 2
max_steps: 200
per_device_train_batch_size: 4
per_device_eval_batch_size: 8
gradient_accumulation_steps: 32

# rlhf args
steps_per_generation: 32
num_generations: 8
rlhf_type: grpo
loss_type: dapo
beta: 0.01
dynamic_sample: true
max_resample_times: 3
epsilon_high: 0.28
num_iterations: 1
reward_funcs: [cgpo_format, cgpo_accuracy, cgpo_det_no_class_aux]
reward_weights: ['0.2', '0.8', '0.1'] # 注意这里必须是字符串形式，否则yaml会读成浮点数，导致报错
external_plugins: [projects/PathVerse/plugin/cgpo_orm.py]
log_completions: true
log_entropy: true
# entropy_loss_coef: 0.005
# entropy_loss_type: full
sync_ref_model: true
ref_model_sync_steps: 50

# rollout args
use_vllm: true
vllm_mode: colocate
vllm_gpu_memory_utilization: 0.3
vllm_max_model_len: 32768
vllm_tensor_parallel_size: 2
vllm_enforce_eager: false # vllm和zero3冲突，这项必须设为true否则vllm报错，zero2不用设置。不用设置，改成配置compilation_config了
vllm_engine_kwargs:
  max_num_batched_tokens: 4096
  compilation_config:
    mode: "none"
sleep_level: 1
max_completion_length: 4096
temperature: 1.0
top_p: 0.99