# model args
model: outputs/PathVerse/1_sft/qwen2-vl-7b-base_0625+rsn-0108_full_VAL_2/v0-20260108-051100/checkpoint-11270
output_dir: outputs/PathVerse/3_rft/qwen2-vl-7b-base#RSN_LOC_0108#SFT
torch_dtype: bfloat16
attn_impl: flash_attn
freeze_vit: true
freeze_aligner: true

# data args
dataset: 
  - 'projects/PathVerse/dataset/nips/3_rft/02_thumbnail_choice.json'
  - 'projects/PathVerse/dataset/nips/3_rft/07_private_patch_choice.json'
split_dataset_ratio: 0.01
dataset_num_proc: 16
load_from_cache_file: true
dataloader_num_workers: 4
max_length: 8192 # 在GRPO时代表max_prompt_length

# log, val and save args
logging_steps: 1
save_strategy: steps
save_steps: 30
save_total_limit: 2
save_only_model: false
report_to: swanlab
swanlab_project: CGPO
swanlab_exp_name: 01Baseline#SFT_GRPO_only-base-format

# train args
train_type: full
deepspeed: zero3
gradient_checkpointing: true
learning_rate: 1e-6
weight_decay: 0.01
warmup_ratio: 0.0
num_train_epochs: 2
max_steps: 150
per_device_train_batch_size: 4
per_device_eval_batch_size: 8
gradient_accumulation_steps: 32

# rlhf args
steps_per_generation: 96
num_generations: 8
rlhf_type: grpo
loss_type: grpo
beta: 0.04
epsilon_high: 0.2
num_iterations: 1
reward_funcs: [cgpo_format, cgpo_accuracy]
reward_weights: ['0.2', '0.8'] # 注意这里必须是字符串形式，否则yaml会读成浮点数，导致报错
external_plugins: [projects/PathVerse/plugin/cgpo_orm.py]
log_completions: true
log_entropy: true

# rollout args
use_vllm: true
vllm_mode: colocate
vllm_gpu_memory_utilization: 0.4
vllm_max_model_len: 32768
vllm_tensor_parallel_size: 2
vllm_enforce_eager: false # vllm和zero3冲突，这项必须设为true否则vllm报错，zero2不用设置。不用设置，改成配置compilation_config了
vllm_engine_kwargs:
  max_num_batched_tokens: 4096
  compilation_config:
    mode: "none"
sleep_level: 1
max_completion_length: 4096
temperature: 1.0
top_p: 0.99