CUDA_VISIBLE_DEVICES="0" \
swift sft \
    --model Qwen/Qwen3-VL-2B-Instruct \
    --output_dir ./outputs/env_test \
    --train_type full \
    --torch_dtype bfloat16 \
    --gradient_checkpointing true \
    --attn_impl sdpa \
    --dataset 'AI-ModelScope/alpaca-gpt4-data-zh#50' \
    --num_train_epochs 1 \
    --per_device_train_batch_size 1 \
    --per_device_eval_batch_size 1 \
    --learning_rate 1e-4 \
    --gradient_accumulation_steps 16 \
    --eval_steps 50 \
    --save_steps 50 \
    --save_total_limit 2 \
    --logging_steps 1 \
    --max_length 2048 \
    --system 'You are a helpful assistant.' \
    --warmup_ratio 0.05 \
    --dataloader_num_workers 4 \
    --use_hf false