# config for reproduce DAPO baseline on ViRL39K in VPPO

# VPPO args
entropy_loss_coef: 0.06
entropy_loss_type: sampled
corrupt_image: random_patch
corrupt_image_kwargs:
  black_prob: 0.5
corrupt_image_position: completion
top_perception_quantile: 0.4
perception_thr_granularity: completion
kl_prcp_reference: old
vppo_use_advantage_shaping: true
vppo_advantage_scaling_min: 0.9

# model args
torch_dtype: bfloat16
attn_impl: flash_attn
freeze_vit: false
freeze_aligner: false

# data args
dataset: 'hf::PAPOGalaxy/PAPO_ViRL39K_train'
val_dataset: 'hf::PAPOGalaxy/PAPO_MMK12_test'
dataset_num_proc: 8
load_from_cache_file: true
dataloader_num_workers: 4
max_length: 4096 # 在GRPO时代表max_prompt_length

# train args
train_type: full
deepspeed: zero3
gradient_checkpointing: true
num_train_epochs: 2
per_device_train_batch_size: 4
per_device_eval_batch_size: 8
gradient_accumulation_steps: 32
learning_rate: 1e-6
weight_decay: 0.01
warmup_ratio: 0.0
lr_scheduler_type: constant

# log, val and save args
logging_steps: 1
save_strategy: steps
save_steps: 150
save_total_limit: 2
save_only_model: false
report_to: swanlab
swanlab_project: VPPO-Reproduce

# rlhf args
rlhf_type: grpo
loss_type: dapo
num_generations: 8
steps_per_generation: 96
beta: 0
epsilon_high: 0.28
dynamic_sample: true
max_resample_times: 3
num_iterations: 1
reward_funcs: papo_accuracy
external_plugins: [projects/baselines/PAPO/reward_function.py]
log_completions: true
log_entropy: true

# rollout args
use_vllm: true
vllm_mode: colocate
vllm_gpu_memory_utilization: 0.4
vllm_tensor_parallel_size: 2
vllm_enforce_eager: false # vllm和zero3冲突，这项必须设为true否则vllm报错，zero2不用设置。不用设置，改成配置compilation_config了
vllm_engine_kwargs:
  max_num_batched_tokens: 4096
  compilation_config:
    mode: "none"
sleep_level: 1
max_completion_length: 2048
temperature: 1.0
top_p: 0.99